artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Akorikk/DATA/blob/main/data/oil_retail_history.csv
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion