artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Akorikk/DATA/raw/refs/heads/main/oil_retail_history.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts\data_ingestion\oil_retail_history.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/oil_retail_history.csv
  processed_data: artifacts/data_transformation/processed.csv
  train_data: artifacts/data_transformation/train.csv
  test_data: artifacts/data_transformation/test.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data: artifacts/data_transformation/train.csv
  test_data: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib

